---
params:
  data: "data"
  result: "result"
  location: 20352
  name: Fort Lier (3010)
  n_winter: 24
---

```{r}
#| label: setup
#| include: false
library(batanalysis)
library(git2rdata)
library(sf)
library(tidyverse)
data_root <- repository(params$data)
```

```{r}
#| label: read-data
file.path("data", "hibernation", "locations") |>
  verify_vc(
    root = data_root, variables = c("id", "longitude", "latitude")
  ) |>
  filter(.data$id == params$location) |>
  st_as_sf(coords = c("longitude", "latitude"), crs = 4267) -> mainlocation
```

# Ligging van het object

```{r}
#| label: cap-format
locatie_cap <- "De omgeving in een straal van %s rond %s."
```

```{r}
#| label: fig-kaart-regio
#| fig.cap: !expr 'sprintf(locatie_cap, "20 km", params$name)'
#| fig-height: 5
mainlocation |>
  st_transform(crs = 31370) |>
  st_buffer(20e3) -> region_buffer
region_buffer |>
  st_buffer(5e3) |>
  st_bbox() |>
  st_transform(crs = 4267) |>
  osm_tile(extra_zoom = 1) -> osm_raw_region
mainlocation |>
  ggplot() +
  pmap(osm_raw_region, annotation_raster, interpolate = FALSE) +
  annotate(
    "text", Inf, -Inf, label = "\U00a9 OpenStreetMap contributors", vjust = 0,
    hjust = 1, size = 2, colour = "black"
  ) +
  geom_sf(
    data = region_buffer, fill = NA, colour = "black"
  ) +
  geom_sf() +
  theme(
    axis.title = element_blank(), plot.background = element_rect(fill = NA)
  )
```

```{r}
#| label: fig-kaart-lokaal
#| fig.cap: !expr 'sprintf(locatie_cap, "1 km", params$name)'
#| fig-height: 5
mainlocation |>
  st_transform(crs = 31370) |>
  st_buffer(1000) -> region_buffer
region_buffer |>
  st_buffer(250) |>
  st_bbox() |>
  st_transform(crs = 4267) |>
  osm_tile(extra_zoom = 1) -> osm_raw_region
mainlocation |>
  ggplot() +
  pmap(osm_raw_region, annotation_raster, interpolate = FALSE) +
  annotate(
    "text", Inf, -Inf, label = "\U00a9 OpenStreetMap contributors", vjust = 0,
    hjust = 1, size = 2, colour = "black"
  ) +
  geom_sf(
    data = region_buffer, fill = NA, colour = "black"
  ) +
  geom_sf() +
  theme(
    axis.title = element_blank(), plot.background = element_rect(fill = NA)
  )
```

```{r}
#| label: fig-kaart-detail
#| fig.cap: !expr 'sprintf(locatie_cap, "200 m", params$name)'
#| fig-height: 5
mainlocation |>
  st_transform(crs = 31370) |>
  st_buffer(250) -> region_buffer
region_buffer |>
  st_buffer(50) |>
  st_bbox() |>
  st_transform(crs = 4267) |>
  osm_tile(extra_zoom = 1) -> osm_raw_region
mainlocation |>
  ggplot() +
  pmap(osm_raw_region, annotation_raster, interpolate = FALSE) +
  annotate(
    "text", Inf, -Inf, label = "\U00a9 OpenStreetMap contributors", vjust = 0,
    hjust = 1, size = 2, colour = "black"
  ) +
  geom_sf(
    data = region_buffer, fill = NA, colour = "black"
  ) +
  geom_sf() +
  theme(
    axis.title = element_blank(), plot.background = element_rect(fill = NA)
  )
```
